"""Initial migration

Revision ID: 2076d9520db9
Revises: fbee1c24456f
Create Date: 2024-12-09 20:37:23.500037

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2076d9520db9'
down_revision = 'fbee1c24456f'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('artboard', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_artboard_user', 'user', ['user_id'], ['id'])  # Added a name


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artboard', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('content',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
